### ISSUE TITLE
可以添加F5刷新后保持tab吗

### ISSUE THREAD

**Issue by simplast** [theprimone/ant-design-pro-plus#12]

**Comment by theprimone** [comment]
保持 tab 是指的 F5 刷新之后恢复到上次的 tab 状态？

**Comment by theprimone** [comment]
> 可能用户习惯用F5，刷新后标签页能不能继续保持以前的状态。

这样有个问题，如果已经打开了很多 tab，那么刷新之后恢复的话，那一瞬间请求大概率很多。个人觉得还是用户重新打开相关页面更合适一些。

**Comment by theprimone** [comment]
或者说假装打开上次的 tab，切过去再渲染出来？有这个特性的话那就会一直恢复上次打开的 tab 了，毕竟不知道用户是刷新还是关闭页面。

**Comment by simplast** [comment]
是的，假装。F5其实只会拿到F5前激活的tab，其余的没有内容

**Comment by theprimone** [comment]
https://stackoverflow.com/questions/11453741/javascript-beforeunload-detect-refresh-versus-close 看了一下这个，刷新应该是尽可能的知道，如果是通过按键的方式的话。这个功能挺有意思的，我争取这周搞定。

**Comment by simplast** [comment]
如果直接去改tab数据来源，把来源直接存到sessionStorage里面，会不会更方便一点，渲染tab都是依靠本地存储的数据，那就自动可以不用在刷新前后写额外逻辑了。

**Comment by theprimone** [comment]
> 如果直接去改tab数据来源，把来源直接存到sessionStorage里面，会不会更方便一点，渲染tab都是依靠本地存储的数据，那就可以不用在刷新前后写额外逻辑了。

计划还是给个配置，假装打开也需要额外的逻辑来阻止页面渲染的啊，不然恢复了发送的请求可能太多了，当然也可以给个配置不阻止 😂

**Comment by theprimone** [comment]
今天得空考虑了一下具体实现，核心逻辑都得改造一下，争取清明假期结束前搞定吧 😂

**Comment by theprimone** [comment]
抽空解决了，可以看看在线实例的效果
