### ISSUE TITLE
怎么在routeTab里面打开iframe  新增tab? 新增tab之后又怎么关闭对应的父级tab呢？（iframe嵌套的是vue项目的页面）

### ISSUE THREAD

**Issue by zzjyr1314** [theprimone/ant-design-pro-plus#13]
![1](https://user-images.githubusercontent.com/81467687/117749968-34028500-b245-11eb-9432-8302a8e93fc9.png)
![2](https://user-images.githubusercontent.com/81467687/117749973-3533b200-b245-11eb-9609-44432f3a91b0.png)
![3](https://user-images.githubusercontent.com/81467687/117749975-35cc4880-b245-11eb-91ab-a6c0c62445bb.png)
![4](https://user-images.githubusercontent.com/81467687/117749977-35cc4880-b245-11eb-8965-437e57dd40b2.png)

**Comment by theprimone** [comment]
不应该直接改 originalMenuData 吧，你这个还需要打开多个 iframe 吗？如果点两次才行的话应该跟 React 的异步更新有关。

你可以先把具体需求说清楚，我帮你看看怎么做更好一些。

**Comment by zzjyr1314** [comment]
问题一： 图一操作步骤为：点击嵌入的iframe页的按钮，要在tabs里打开新的iframe页，操作一次按钮会出现2个tab(一个是404，一个是填写接待记录)。虽然知道在useEffect中监听originalMenuData并不合适，但找不到更优解。
问题二： 图二新增产品按钮实际上也是在tabs中新增一个iframe页。此时，涉及回调参数。需求是：在新增产品页选中产品后，关闭当前窗口，代参回到消费开单页。通过postMessage 可以获取vue项目传递的信息，却在react项目中无法关闭新增产品页，回到消费开单页。

**Comment by zzjyr1314** [comment]
关键就是嵌套的iframe页面很多  不可能在路由里面定义相关的页面组件

**Comment by theprimone** [comment]
再多也知道那些页面需要 iframe 嵌套的，不预先定义好相关页面路由的话，react-router 怎么去渲染呢。懒得一个个定义的话可以试试 [patchRoutes({ routes })](https://umijs.org/zh-CN/docs/runtime-config#patchroutes-routes-) 把相关的页面 patch 进去，指向的页面组件为同一个，即自动加载 iframe 页面。

或者使用标签页功能的路由参数模式试试

> 两种标签页模式可选
> - 基于路由，每个路由只渲染一个标签页
> - 基于路由参数，计算出每个路由的所有参数的哈希值，不同的哈希值渲染不同的标签页

**Comment by theprimone** [comment]
Closing by inactive
