### ISSUE TITLE
nested routes?

### ISSUE THREAD

**Issue by anako126n** [theprimone/ant-design-pro-plus#26]
Hi,

I've tried in various ways to use `Mode.Dynamic` without any success, it always defaults to most top level.

```js
  {
    path: '/admin',
    name: 'admin',
    icon: 'crown',
    access: 'canAdmin',
    component: './Admin',
    routes: [
      {
        path: '/admin/page', name: 'page', icon: 'smile', component: './Welcome',
        routes: [
          {
            path: '/admin/page/:id', name: 'edit.page', icon: 'smile', component: './Welcome',
          },
          {component: './404'},
        ],
      },
      {
        path: '/admin/pages', name: 'pages', icon: 'smile', component: './Welcome',
      },
      {component: './404'},
    ],
  },
```

The above route generates the following
```
admin
admin/page
admin/page/:id
admin/pages
```

Navigating through these pages will always give me one tab only and overwrites the pathname of the tab.

![image](https://user-images.githubusercontent.com/3118846/147310129-30aa3cf2-a225-4090-9434-378eeda670b5.png)

It looks like the getMetadata function is always returning an item with `renderKey: /admin`.  

What am I missing?

thanks!

**Comment by theprimone** [comment]
https://github.com/theprimone/use-switch-tabs/blob/master/src/utils.tsx#L45 The match pattern cause the result, you can try to change `admin/pages` to `admin/all-page`?

On the other hand, the route should be named according to the business, generally. A little wired route definitions :joy:

**Comment by theprimone** [comment]
Not exactly above.

Routes to tabs only first level route is valid, like: /welcome, /admin (match pattern you can see above). So it works as expected. you can try route definitions like below:

- /welcome
- /admins
- /admin
	- /admin/:id

**Comment by anako126n** [comment]
route definition is just for playing, nevertheless thanks for pointing towards the right direction.

It is possible to achieve what I wanted by defining components only on the children routes, now my output is as follows

![image](https://user-images.githubusercontent.com/3118846/147359768-2c20f69e-b6f2-4352-ba11-b67e28c6dde1.png)

and the routes definition

```js
{
    path: '/admin',
    name: 'admin',
    access: 'canAdmin',
    routes: [
      {
        path: '/admin/all-pages',
        name: 'all-pages',
        routes: [
          {
            path: '/admin/all-pages',
            redirect: '/admin/all-pages/test',
          },
          {
            path: '/admin/all-pages/page/:id',
            hideInMenu: true,
            name: 'test',
            component: './Welcome',
          },
          {
            path: '/admin/all-pages/test',
            name: 'test',
            component: './Welcome',
          },
          {
            path: '/admin/all-pages/sub-test',
            name: 'sub-test',
            routes: [
              {
                path: '/admin/all-pages/sub-test',
                redirect: '/admin/all-pages/sub-test/test',
              },
              {
                path: '/admin/all-pages/sub-test/test',
                name: 'test',
                component: './Welcome',
              },
              {
                path: '/admin/all-pages/sub-test/:id',
                hideInMenu: true,
                name: 'sub-test',
                component: './Welcome',
              },
              {component: './404'}
            ],
          },
        ],
      }
    ],
}
```

**Comment by theprimone** [comment]
Business scenarios that are not understood. Generally speaking, only first level routes need to be displayed with tabs. Nested routes should render inside tab panel, unless you want to render tabs in a tab panel...

**Comment by theprimone** [comment]
Close as stale.

**Comment by theprimone** [comment]
Close as stale.
