### ISSUE TITLE
对antd pro layout 是mix的，tab会多出一个

### ISSUE THREAD

**Issue by imgoby** [theprimone/ant-design-pro-plus#44]
（1）在mix布局下，点击/aa，会跳转到/aa/bb，这时，页标签有两个：/aa、/aa/bb，有方法把/aa的页签去掉吗？只保留/aa/bb这个

```js
{
    path: '/aa',
    name: 'aa',
    icon: 'dashboard',
    routes: [
        {
            name: 'bb',
            icon: 'smile',
            path: '/aa/bb',
            component: './aa/bb',
        },
        {
            path: '/aa',
            redirect: '/aa/bb',
        },
    ],
}
```

**Comment by imgoby** [comment]
mix布局：
![image](https://user-images.githubusercontent.com/27885492/171319727-8660f3d7-f179-4fa6-b9c7-51dcfd83d003.png)

出现问题，
![image](https://user-images.githubusercontent.com/27885492/171320428-dfc99b9d-b5e4-469b-b560-501a44d50d75.png)


![image](https://user-images.githubusercontent.com/27885492/171320376-c74613ce-9ed6-4cfd-b24d-f94fc67d4171.png)

**Comment by imgoby** [comment]
设置了分割菜单，这就让一级菜单可以点击了。但一级菜单是一个目录。所以就有问题了

**Comment by yunsii** [comment]
自动分割菜单这个功能是新 feature 吧，我研究一下再答复你，会尽快修复的。

**Comment by imgoby** [comment]
谢谢

**Comment by yunsii** [comment]
问题解决了，由于 React Router 的 redirect 逻辑之前一直没处理 😂 按照之前 ant design pro 的菜单逻辑是不会自动触发 redirect 的，现在这个自动分割菜单的功能就会触发 redirect 了。

当前项目内实现可参考 commit：https://github.com/yunsii/ant-design-pro-plus/commit/acdc50a0594895d0ff35777b76328b86642a71b5
use-switch-tabs 中的处理：https://github.com/yunsii/use-switch-tabs/blob/master/src/utils.tsx#L45

**Comment by imgoby** [comment]
thanku
